[tool.black]
line-length = 200
target-version = ['py39']
include = '\.pyi?$'

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true
disable_error_code = "import-untyped"
exclude = ["stubs/*"]
follow_imports = "skip"
follow_imports_for_stubs = false
mypy_path = "stubs"

[[tool.mypy.overrides]]
module = ["stubs.*", "stubs.open_webui.*"]
disallow_untyped_defs = false
check_untyped_defs = false
